Repository unb-mds/2024-1-Squad-10, pull requests merged in 2024-08, with the labels that each got.

#52 Refatorei o código do rank das empresas, para facilitar a criação de testes unitários
  frontend/pages/01_Rank_empresas.py
Labels: enhancement

#57 Adicionando script para abrir uma issue automática para revisão do arquivo de contratos
  .github/workflows/10cnpj.yml
  .github/workflows/11ordenacao.yml
  .github/workflows/1contratos21_22.yml
  .github/workflows/2contratos22_23.yml
  .github/workflows/3contratos23_24_1.yml
  .github/workflows/4contratos23_24_2.yml
  .github/workflows/5contratos24_25.yml
  .github/workflows/6contratos25_26.yml
  .github/workflows/7contratos_erro.yml
  .github/workflows/8confirmar_contratos.yml
  .github/workflows/9empresa.yml
Labels: enhancement

#63 Refatorações usando Pylint e Markdownlint
  docs/Sprint.md
  frontend/Menu.py
Labels: documentation

#64 Encapsulando o código em funções para facilitar testes unitários
  Dados/info_empresa.py
Labels: enhancement

#65 teste unitario salvamento csv
  tests/test_info.empresa/test_salvamento_contratos.py
Labels: enhancement

#69 criação do codeclimate para relatorio e atualizações pendentes
  .github/codeclimate.yml
  Dados/test_coleta_api.py
  contratos_OFICIAL.json
Labels: enhancement

#74 corrigindo erros para deploy funcionar corretamente
  frontend/Menu.py
  frontend/pages/01_Rank_empresas.py
  frontend/pages/02_Rank_dos_órgãos.py
  requirements.txt
Labels: bug

#94 Refatoração do código info_empresa
  Dados/info_empresa.py
Labels: enhancement

#108 incluindo documentação da arquitetura da pipeline
  docs/Arquitetura_pipeline.md
Labels: documentation

#109 Refatoração do código de arquitetura do projeto
  docs/Arquitetura.md
  docs/Arquitetura_pipeline.md
Labels: enhancement
